trigger: none

pool: 
  vmImage: ubuntu-latest

parameters:
- name: resourcegroup
  displayName: 'Select resource group'
  type: string
  default: prodrg
  values:
    - devrg
    - qarg
    - prodrg


stages:
- stage: FetchFromKeyVault
  displayName: 'Stage - Fetch Resource Group Secret and Save'
  variables:
    rg: "prodrg"
  jobs:
  - job: FetchRG
    displayName: 'Fetch Resource Group Name from Key Vault'
    steps:
    - task: AzureKeyVault@2
      name: FetchSecrets
      inputs:
        azureSubscription: 'SubscriptionScopedArtemis'
        KeyVaultName: 'CaseKV01'
        SecretsFilter: '*'
        RunAsPreJob: true

    - script: |
        echo "Here is the prod rg value ${{parameters.resourcegroup}}"
        echo "Here is the prod rg value $(prodrg)"
        echo "$(prodrg)" > prod.txt

      displayName: 'Write Resource Group Name to File'
      name: secretStep

